plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/Darren/Sites/TrackHair Website/TrackHairWeb/_site"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build && cp -R assets _site/"

[build.environment]
RUBY_VERSION = "3.1.4"
NODE_VERSION = "14.18.0"
PYTHON = "python3.10"
SHARP_IGNORE_GLOBAL_LIBVIPS = "1"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]